/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sofware_contable;

import conexion.conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class diseño_login extends javax.swing.JFrame {

    public String usuario ="";
    private String password="";
    public diseño_login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Field_user = new javax.swing.JTextField();
        btn_ingreso = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        Field_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_userActionPerformed(evt);
            }
        });
        getContentPane().add(Field_user);
        Field_user.setBounds(500, 230, 190, 30);

        btn_ingreso.setBackground(new java.awt.Color(0, 255, 0));
        btn_ingreso.setText("ingresar");
        btn_ingreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresoMouseClicked(evt);
            }
        });
        btn_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingreso);
        btn_ingreso.setBounds(591, 370, 90, 23);

        btn_salir.setBackground(new java.awt.Color(255, 0, 0));
        btn_salir.setText("salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir);
        btn_salir.setBounds(490, 370, 90, 23);

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordField);
        PasswordField.setBounds(500, 310, 190, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sofware_contable/imagenes/front.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(800, 500));
        jLabel3.setMinimumSize(new java.awt.Dimension(800, 500));
        jLabel3.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 680, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int rectificar()
    {
        int contador=0;
            if(Field_user.getText().equals(" ") )
            {
                contador++;
            }
            if(PasswordField.getText().equals(" "))
            {
                contador++;
            }
        return contador;
    }
    boolean validar(String username, String userpass){
        conectar cc=new conectar();
        Connection cn=cc.conexion();
        String sql;
            sql="SELECT * FROM usuarios where usuario = '";
            sql += username+"'";
        try{
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
            {
                if(rs.getString("contra").equals(userpass))
                {
                    return true;
                }
            }
        }catch(SQLException ex){
            Logger.getLogger(datos.class.getName()).log(Level.SEVERE,null,ex);
        }
        return false;
    }
    private void Field_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_userActionPerformed

    private void btn_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresoActionPerformed
        usuario = Field_user.getText();
        password = PasswordField.getText();
        if(rectificar()==0)
        {
            if(validar(usuario, password)==true)
            {
                diseño dis=new diseño();
                dis.setVisible(true);
                this.dispose();
            }else
            {
                JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos");
            }
        }
        if(rectificar()==2)
        {
            JOptionPane.showMessageDialog(null, "los campos estan vacios por favor ingrese datos");
        }
        
    }//GEN-LAST:event_btn_ingresoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
       System.exit(WIDTH);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_ingresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresoMouseClicked
       diseño dis=new diseño();
       dis.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btn_ingresoMouseClicked

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diseño_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diseño_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diseño_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diseño_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                apariencia ap = new apariencia();
                ap.recuadro();
                new diseño_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Field_user;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton btn_ingreso;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
